;/* Version 390afaf42616833fafe738af3dd48b5e v:4.4.3.560, c:803257b4fc230f8e2aaf9ec7c320f318796c3545, b:4.4.3.560 n:INTERNAL-BUILD */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var g=window.ADRUM;if(g&&g.q&&!0!==window["adrum-disable"]){var x=window.console,z=x&&"function"==typeof x.log?x:{log:function(){}},u=this&&this.hh||function(){var a=Object.Sj||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var e in f)f.hasOwnProperty(e)&&(a[e]=f[e])};return function(b,f){function e(){this.constructor=b}a(b,f);b.prototype=null===f?Object.create(f):(e.prototype=f.prototype,new e)}}();(function(a){(function(b){b.ha=function(f){function e(a){return a.replace(/\s/g,
"")===d}var c={a:[1,2,3,"str"]},d='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&b.isFunction(JSON.stringify)&&e(JSON.stringify(c)))return JSON.stringify(f);if("undefined"!==typeof Object&&Object&&b.isFunction(Object.toJSON)&&e(Object.toJSON(c)))return Object.toJSON(f);a.error("M83");return null};b.Lb=function(f,e,c){var d=f,h=c;"xhr"===c&&(d=document.createElement("div"),f.appendChild(d),h="xhr_"+f.getElementsByTagName("div").length);f=document.createElement("p");f.innerHTML="Script loaded from "+
a.conf.adrumExtUrl+". Metrics collected are:";d.appendChild(f);f=document.createElement("table");f.id="ADRUM_"+h;var h=document.createElement("tbody"),n;for(n in e){c=document.createElement("tr");var b=document.createElement("td");b.innerHTML=n;b.className="name";var k=document.createElement("td");k.innerHTML=String(e[n]);k.className="value";c.appendChild(b);c.appendChild(k);h.appendChild(c)}f.appendChild(h);d.appendChild(f)};b.Oh=function(){function a(e,c){try{if("object"!=typeof e)return String(e);
if(0<=b.Ua(c,e))return"Already visited";c.push(e);var d;if(b.isArray(e)){for(var h="[ ",n=0;n<e.length;n++)0!=n&&(h+=", "),h+=a(e[n],c);d=h+" ]"}else{var h="{ ",n=!0,m;for(m in e)n?n=!1:h+=", ",h+=a(m,c)+" => "+a(e[m],c);d=h+" }"}return d}catch(k){return"dumpObject failed: "+k}}return function(e){return a(e,[])}}();b.Ua=b.isFunction(Array.prototype.indexOf)?function(a,e){return a.indexOf(e)}:function(a,e){for(var c=0;c<a.length;c++)if(a[c]==e)return c;return-1};b.compareWindows=function(a,e){return a==
e};b.Tb=function(a,e,c,d,h){if(!b.isDefined(e))return e;if(b.isArray(e)){a=[];for(var n=0,m=e.length;n<m;n++)a[n]=b.Tb(n,e[n],c,d,h);return a}if(b.isFunction(e))return e;if(b.isObject(e)){a={};for(n in e)b.hasOwnPropertyDefined(e,n)&&(a[c(n)]=h&&h(n)?e[n]:b.Tb(n,e[n],c,d,h));return a}return d(a,e)};b.$i=function(a){var e=[],c;for(c in a)b.hasOwnPropertyDefined(a,c)&&e.push([c,a[c]]);return e};b.ck=function(){try{localStorage.setItem("try","try");var a=localStorage.getItem("try");localStorage.removeItem("try");
return"try"===a}catch(e){return!1}};b.bk=function(){try{var a=b.ha({v:1});return 1===JSON.parse(a).v}catch(e){return!1}};b.dk=function(){return b.isFunction(window.postMessage)};b.Fh=function(a,e){var c=document.createElement("div");c.innerHTML='<iframe id="'+e+'" src='+a+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(c);return document.getElementById(e)};b.Pj=function(a,e){b.isDefined(e)&&(a.parentPageName=e)};b.Zb=function(a){return b.isNumber(a)&&
isFinite(a)&&Math.floor(a)===a};b.Kd=function(b){a.log(b);z.log(b)}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(a){a.pf=function(a){return/^[0-9]+$/.test(a)?Number(a):null};a.me=function(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){function f(h){var d=h.split("\r\n"),c=/^\s*ADRUM_(\d+): (.+)\s*$/i;h=[];for(var e=0;e<d.length;e++){var b=d[e];try{var f=c.exec(b);f&&h.push([Number(f[1]),f[2]])}catch(g){a.exception(g,
"M86",b)}}Array.prototype.sort.call(h,function(a,h){return a[0]-h[0]});f=[];for(d=0;d<h.length;d++)f.push(h[d][1]);return f}var e=a.utils.hasOwnPropertyDefined,c=null,d=null;b.ce=function(){d||(d=b.Ce(b.kc(b.cookieMetadataChunks),b.kc(a.footerMetadataChunks)));return d};b.getPageGUID=function(){var h=a.monitor.DOMEventsMonitor,d=a.utils.isObject(h.currentBasePage)&&a.utils.isFunction(h.currentBasePage.guid);if(!c){var e=b.ce();c=e&&e.clientRequestGUID||(d?h.currentBasePage.guid():a.utils.generateGUID())}return c};
b.pi=function(h){h=f(h);a.log("M84",h);return b.Ce(b.kc(h))};b.Ce=function(h,d){function c(h){for(var d=0;d<h.length;d++){var n=h[d];n!=e&&0>a.utils.Ua(p,n)&&p.push(n)}}if(!h||0>=h.ka.length)return null;d||(d=h);var e;if(0<d.ka.length){if(e=d.ka[0],0>a.utils.Ua(h.ka,e))return null}else return a.error("M85"),null;var f=d.serverSnapshotType||h.serverSnapshotType,g=d.hasEntryPointErrors||h.hasEntryPointErrors,p=[];c(h.ka);c(d.ka);var s={clientRequestGUID:e,btGlobalAccountName:h.btGlobalAccountName};
0<p.length&&(s.otherClientRequestGUIDs=p);0<b.Be(h.btTime,d.btTime).length&&(s.btTime=b.Be(h.btTime,d.btTime));null!==f&&(s.serverSnapshotType=f);null!==g&&(s.hasEntryPointErrors=g);return s};b.Be=function(a,d){for(var c=a.concat(d),b={},f={},g=0;g<c.length;g++){var p=c[g];p.id in b||(b[p.id]=-1);b[p.id]=Math.max(b[p.id],p.duration);p.id in f||(f[p.id]=-1);f[p.id]=Math.max(f[p.id],p.ert)}var c=[],s;for(s in b)e(b,s)&&c.push({id:s,duration:b[s],ert:f[s]});return c};b.kc=function(h){if(!a.utils.isArray(h))return null;
for(var d=[],c=null,e=[],b=null,f=null,g=0;g<h.length;g++){var s=h[g];if("string"!==typeof s)return null;s=s.replace(/^"|"$/g,"");s=decodeURIComponent(s).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===s.length){var t=s[1];switch(s[0]){case "clientRequestGUID":case "g":d.push(t);break;case "btId":case "i":e.push({id:t,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===e.length)return null;s=a.utils.pf(t);if(!a.utils.me(s)||-1>s)return null;e[e.length-1].duration=s;break;case "btERT":case "e":if(0===
e.length)return null;s=a.utils.pf(t);if(!a.utils.me(s)||-1>s)return null;e[e.length-1].ert=s;break;case "serverSnapshotType":case "s":b=t;break;case "globalAccountName":case "n":c=t;break;case "hasEntryPointErrors":case "h":f=t}}}return 0===d.length?null:{ka:d,btGlobalAccountName:c,btTime:e,serverSnapshotType:b,hasEntryPointErrors:f}};b.pl=f})(a.correlation||(a.correlation={}))})(g||(g={}));(function(a){var b=a.conf||(a.conf={});b.Gk=3E3;b.xf=a.isDebug;b.dh=1E3;b.zg=2;b.yg=5;b.tg=5;b.ug=20;b.dd=5E3;
b.wa=512;b.Yf=10;b.Xf=64;b.Kg=10;b.Jg=10;b.Fg=300;b.Cg=2048;b.xa=2048;b.Mg=760;b.we={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",userDataBoolean:"udb",
userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",parentPageName:"an",
geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(g||(g={}));(function(a){a=a.beacons||(a.beacons={});a.numBeaconsSent=0;a.beaconsSent=[]})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.send=function(c,d){var h=(d?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.corsEndpointPath+"/"+a.conf.appKey+"/adrum",e;a.utils.isFunction(a.xhrConstructor)&&a.utils.isFunction(a.xhrOpen)?(e=new a.xhrConstructor,a.xhrOpen.call(e,
"POST",h)):(e=new XMLHttpRequest,e.open("POST",h));e.setRequestHeader("Content-type","text/plain");var f=a.utils.ha(c);null!=f&&(a.utils.isFunction(a.xhrSend)?a.xhrSend.call(e,f):e.send(f),a.log("M87"+h+"\n"),a.log("<hr/>"),a.isDebug&&b.beaconsSent.push(c),b.numBeaconsSent+=1)};return e}();b.Tf=f})(a.beacons||(a.beacons={}))})(g||(g={}));g||(g={});(function(a){var b=function(){function b(a,c,d){this.ab=a;this.zi=c;this.Gc=d}b.prototype.Rb=function(){try{return b.Zd(this.zi.ADRUM)}catch(e){return a.error("M88"),
b.Zd(a)}};b.Zd=function(a){return a.correlation.getPageGUID()};return b}();a.Pf=b})(g||(g={}));(function(a){a.beacons||(a.beacons={})})(g||(g={}));(function(a){(function(a){var f=function(){function e(){this.Xa=[];this.Mb={}}e.prototype.$a=function(c){if(!c)return"";if(a.hasOwnPropertyDefined(this.Mb,c))return this.Mb[c];var d=this.Xa.length;this.Mb[c]=d;this.Xa[d]=c;return d};return e}();a.cd=f})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.map,e=function(){function a(){}
a.Xj=function(a){a=(a||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var h={};a[1]&&(h.protocol=a[1].substring(0,a[1].length-3));a[2]&&(h.path=a[2]);a[3]&&(h.Bj=a[3]);a[4]&&(h.anchor=a[4]);return h};a.Sh=function(d,h){var e=a.Xj(d),b="";e.protocol&&(b+=h.$a(e.protocol),b+="://");e.path&&(b+=f(e.path.split("/"),h.$a,h).join("/"));return b+=f([e.Bj,e.anchor],function(a){return a?a[0]+h.$a(a.slice(1)):""},h).join("")};a.Qh=function(a,h){return""+h.$a(a)};return a}();b.Sc=e})(a.beacons||
(a.beacons={}))})(g||(g={}));(function(a){(function(b){(function(b){function e(){var h=null,c=null;try{h=localStorage[d]}catch(e){}if(h)try{h=c=JSON.parse(h),a.utils.isObject(h)&&a.utils.isNumber(h[m])&&-1<h[m]?g=c:a.error("M89")}catch(b){a.exception(b,"M90");try{delete localStorage[d]}catch(n){a.exception(n,"M91")}}}function c(){try{var c=a.channel,e=g[h]||g[n],b=c&&c.L&&c.L.K&&c.L.K.id||(a.utils.isString(e)?e:a.utils.generateGUID());g[h]=g[n]=b;localStorage[d]=a.utils.ha(g)}catch(f){}}var d="ADRUM_CLIENTINFO",
h="agentId",n="clientId",m="seqId",g;e();g||(g={seqId:0});c();b.gi=function(){e();var a=g[m]++;c();return a}})(b.Hd||(b.Hd={}))})(a.hf||(a.hf={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.urlCapture={filterURLQuery:!1};this.Ue=/;jsessionid=[^/?]+/;b.mergeJSON(this.urlCapture,a.conf.userConf.urlCapture);b.isBoolean(this.urlCapture.filterURLQuery)||b.isArray(this.urlCapture.filterURLQuery)||(a.log("M92"),this.urlCapture.filterURLQuery=!1)}e.Wj=function(a){for(var d=
0,h=0;h<a.length;h++)d=(d<<5)-d+a.charCodeAt(h),d|=0;return d};e.prototype.ni=function(a){var d="",h,e;if(!b.isString(a))return"";h=a.indexOf("?")+1;0<h&&(e=a.indexOf("#"),0>e?d=a.substring(h):h<=e&&(d=a.substring(h,e)));return d};e.prototype.Wh=function(a){var d="",h=this.urlCapture.filterURLQuery,e={},f=0,g,q,r;if(!b.isString(a)||""===a)return"";if(!1===h)return a;g=this.ni(a);if(""===g)return a;if(b.isArray(h)){for(r=0;r<h.length;r++)e[h[r]]=!0;h=g+"&";for(r=0;r<h.length;r++)switch(h[r]){case "=":q=
h.substring(f,r);break;case "&":case ";":q=q||h.substring(f,r),r++,e[q]||(d+=h.substring(f,r)),f=r,q=null}d=d.substring(0,d.length-1)}""==d&&(g="?"+g);return a.replace(g,d)};e.prototype.aa=function(a){if(null===a||void 0===a)return null;if(""===a)return"";var d=a.match(this.Ue),h=a;if(null!=d){var e=a.indexOf("?");if(0>e||e>d.index)h=a.replace(this.Ue,"")}return h=this.Wh(h)};e.prototype.Td=function(a){if(null===a||void 0===a)return null;var d=a.indexOf("?"),h=a.indexOf("#");0>d&&(d=Number.MAX_VALUE);
0>h&&(h=Number.MAX_VALUE);return a.substring(0,Math.min(d,h))};e.prototype.kj=function(a){if(null===a||void 0===a)return null;var d=this.Td(a);return d+"?"+e.Wj(a.substring(d.length))};return e}();b.Lk=f;b.M=new f})(a.utils||(a.utils={}))})(g||(g={}));(function(a){a=a.ra||(a.ra={});a.qa||(a.qa={})})(g||(g={}));(function(a){a=a.ra||(a.ra={});a.qa||(a.qa={})})(g||(g={}));(function(a){(function(b){(function(b){var e=function(){function e(d,h,c){this.Dj=0;this.qc=[];this.ge=!1;this.ti=c;var b=this;a.utils.addEventListener(window,
"message",function(a){b.oj(a)});this.si=a.utils.Fh(h,d)}e.prototype.oj=function(d){var h;try{if(h=JSON.parse(d.data),a.utils.isDefined(h)&&!0===h.success)if(-1===h.id&&"iframe-ready"===h.data)this.ge=!0,this.ti();else{if(this.qc[h.id])this.qc[h.id](h.data)}else a.error("M93",d.data)}catch(e){a.exception(e,"M94")}};e.prototype.send=function(d,h,e,c){if(this.ge){var b=this.Dj++;this.qc[b]=c;this.si.contentWindow.postMessage(a.utils.ha({id:b,action:d,key:h,value:e}),"*")}};e.prototype.generateGUID=function(a,
h){this.send("generateGUID",a,null,h)};return e}();b.Vf=e})(b.qa||(b.qa={}))})(a.ra||(a.ra={}))})(g||(g={}));(function(a){(function(b){var f=function(){function d(){this.yd=new e(d.Kf);this.Gf=new e(d.Mf);this.yk=new c(d.Lf)}d.prototype.init=function(h){this.channel=h;a.utils.ck()&&a.utils.bk()?a.utils.dk()&&d.Vi()?this.nk():this.yf():d.De=!0};d.prototype.yf=function(){var h=this.yd.load();d.Ti(h)||(h={ver:a.conf.agentVer,id:a.utils.generateGUID()},this.yd.save(h));d.K=h};d.prototype.nk=function(){var h=
this.Gf.load();if(d.Ui(h))d.K=h;else{a.log("M95");var e=this;this.yk.load(function(h){h&&(h={ver:a.conf.agentVer,id:h,ttl:(new Date).getTime()+d.Zf},e.Gf.save(h),d.K=h,a.log("M96"))});e=this;a.utils.tryPeriodically(d.Cb,function(){return e.isReady()},function(){e.onReady()},function(){e.fc()})}};d.Vi=function(){return a.conf.userConf&&a.conf.userConf.xd&&a.conf.userConf.xd.enable};d.Ti=function(a){return a&&a.id&&0<a.id.length};d.Ui=function(a){return a&&a.id&&0<a.id.length&&0===a.id.indexOf("XD_")&&
a.ttl>(new Date).getTime()};d.prototype.isReady=function(){return d.De||a.utils.isDefined(d.K)};d.prototype.onReady=function(){this.channel.onResolverReady()};d.prototype.fc=function(){a.log("M97");this.yf();this.channel.onResolverReady()};d.Cb=function(a){return 10<a?-1:[1,50,100,500][a-1]||1E3};return d}();f.Kf="ADRUM_AGENT_INFO";f.Mf="ADRUM_XD_AGENT_INFO";f.Lf="ADRUM_XD_AGENT_ID";f.Zf=6048E5;f.De=!1;b.L=f;var e=function(){function d(a){this.wd=a}d.prototype.load=function(){var h=null;try{var d=
localStorage.getItem(this.wd);d&&(h=JSON.parse(d))}catch(e){a.exception(e,"M98")}return h};d.prototype.save=function(h){try{var d=a.utils.ha(h);d&&localStorage.setItem(this.wd,d)}catch(e){a.exception(e,"M99")}};return d}(),c=function(){function d(a){this.oh=a}d.prototype.load=function(h){var d=this;try{var e=new a.ra.qa.Vf("cross-domain-store-server-iframe",a.conf.adrumXdUrl,function(){e.generateGUID(d.oh,h)})}catch(c){a.exception(c,"M100")}};return d}()})(a.channel||(a.channel={}))})(g||(g={}));
(function(a){(function(b){var f=a.utils.isString,e=a.utils.isNumber,c=function(){function d(){}d.prototype.gb=function(h,e,c){h={ver:a.conf.agentVer,dataType:"R",rootGUID:c.Rb(),events:h};a.channel.L.K&&a.channel.L.K.id&&(h.agentId=a.channel.L.K.id);e&&(h.geo=e);return d.xj(h)};d.xj=function(h){a.isDebug||(h=d.zh(h));return h};d.zh=function(h){var c=new a.utils.cd,g=new a.utils.cd;h=a.utils.Tb(null,h,d.Sb,function(h,q){if(!f(q))return q;if(d.Si(h)){var r=d.Ni(h)&&e(a.conf.userConf.maxUrlLength)?a.conf.userConf.maxUrlLength:
a.conf.wa;q=d.Dc(q,r);q=b.Sc.Sh(q,c)}else q=d.Mi(h)?d.Dc(q,a.conf.Mg):d.Dc(q,a.conf.Cg);d.Hi(h)&&(q=b.Sc.Qh(q,g));return q},d.cj);h[d.Sb("guids")]=g.Xa;h[d.Sb("urlParts")]=c.Xa;return h};d.Si=function(a){return"eventUrl"==a||"parentUrl"==a||"pageReferrer"==a||"pageUrl"==a||"u"==a};d.Hi=function(a){return"eventGUID"==a||"parentGUID"==a||"rootGUID"==a||"clientRequestGUID"==a};d.Mi=function(a){return"userPageName"==a};d.Dc=function(a,d){return a.length>d?a.substr(0,d-3)+"...":a};d.Ni=function(a){return"eventUrl"==
a||"parentUrl"==a||"pageReferrer"==a};d.Sb=function(h){if(a.conf.xf)return h;var d=a.conf.we[h];return"undefined"===typeof d?h:d};d.cj=function(a){a=""+a;return 0===a.indexOf("userData")||"parameter"===a};return d}();b.Sf=c})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.send=function(a,d){for(var h=0;h<a.length;h++)this.Nj(a[h],d)};e.prototype.Nj=function(e,d){var h=(d?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.imageEndpointPath,
f=document.createElement("img");try{f.src=h+e}catch(g){}a.isDebug&&b.beaconsSent.push(e);b.numBeaconsSent+=1};return e}();b.pg=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){a.Ma=function(a,e){if(3>=e)return"...";a.length>e&&(a=a.substring(0,e-3)+"...");return a};a.tf=function(a,e){if(3>=e)return"...";a.length>e&&(a=a.substring(0,(e-3)/2)+"..."+a.substring(a.length-(e-3)/2,a.length));return a};a.jk=function(f,e){f.length<=e||(f=a.Ma(f,e-1),f+=":");return f};a.hk=function(f,
e,c,d,h,n){f=a.jk(f,d);c=a.Ma(c,h);f.length+e.length+c.length>n-3&&(e=a.Ma(e,n-3-f.length-c.length));return 0<c.length?f+"//"+e+":"+c:f+"//"+e};a.ik=function(f,e,c){f=a.map(f,function(d){return a.tf(d,e)});if(f.length>c){var d=f[0];f=f.slice(f.length-c);f.unshift("...");""==d&&f.unshift(d)}return f};a.kk=function(f,e,c,d,h){d=a.hk(f.protocol,f.hostname,f.port,d,h,e);c--;h=a.Ma(f.search,e);c--;var n=a.Ma(f.hash,e);c--;f=f.pathname.split("/");var g="";0<f.length&&(g=f.pop(),g=a.tf(g,e),c--);f=a.ik(f,
e,c);return 0==f.length?d+g+h+n:d+f.join("/")+"/"+g+h+n}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}a.Xb=function(){for(var c=0;c<a.ad.length;c++)a.W[a.ad[c]]=a.R.jg;for(c=0;c<a.Zc.length;c++)a.W[a.Zc[c]]=a.R.dg;a.W.js=a.R.Xg;a.W.css=a.R.CSS;a.W.svg=a.R.Zg;a.W.html=a.R.$c;a.W.htm=a.R.$c};a.Pb=function(a){return a.duration?a.duration:a.responseEnd&&a.startTime?a.responseEnd-a.startTime:-1};a.ae=function(c){var d;return(c=c.pathname)&&-1!=(d=c.lastIndexOf("."))?
a.W[c.substring(d+1,c.length).toLowerCase()]||a.R.jd:a.R.jd};return a}();f.R={jg:"img",Xg:"script",CSS:"css",Zg:"svg",$c:"html",dg:"font",jd:"other"};f.ad="bmp gif jpeg jpg png webp".split(" ");f.Zc=["ttf","woff","otf","eot"];f.W={};a.ya=f;f.Xb()})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(c){function d(a){h.marks.push(0==c[a]?-1:Math.round(c[a]-h.Ie))}this.marks=[];var h=this;this.Ie=c.startTime;this.Fi(c)?(this.Wd=a.Tc,d("startTime"),d("fetchStart")):
(this.Wd=a.md,d("startTime"),d("redirectStart"),d("redirectEnd"),d("fetchStart"),d("domainLookupStart"),d("domainLookupEnd"),d("connectStart"),d("secureConnectionStart"),d("connectEnd"),d("requestStart"),d("responseStart"));d("responseEnd")}a.hi=function(){var c={};c[a.md]=a.Wg;c[a.Tc]=a.Uf;return c};a.prototype.Fi=function(a){return this.da(a.redirectStart)&&this.da(a.redirectEnd)&&(this.da(a.domainLookupStart)||this.da(a.domainLookupEnd)||this.da(a.connectStart)||this.da(a.connectEnd))&&this.da(a.secureConnectionStart)};
a.prototype.da=function(a){return!a||0===a};return a}();f.md=1;f.Tc=2;f.Wg="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd".split(" ");f.Uf=["startTime","fetchStart","responseEnd"];a.ld=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}a.prototype.mb=function(a,d){if(a)return a.slice(0,d)};return a}();a.eg=f})(a.events||(a.events={}))})(g||
(g={}));(function(a){(function(a){var f=function(){function e(){}e.prototype.mb=function(e,d){if(e){if(e.length<=d)return e;for(var h=[],f=0;f<e.length;f++)h.push({sc:e[f],index:f});h.sort(function(d,h){return-(a.ya.Pb(d.sc)-a.ya.Pb(h.sc))});h=h.slice(0,d);h.sort(function(a,d){return a.index-d.index});for(var g=[],f=0;f<h.length;f++)g.push(h[f].sc);return g}};return e}();a.od=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function e(){}e.prototype.mb=function(e,
d){if(e){if(e.length<=d)return e;for(var h=1,f=Math.floor(Number.MAX_VALUE/4),g=e.length;h<f;){for(var k=e.length-1;0<=k;k--)if(a.ya.Pb(e[k])<h&&(e.splice(k,1),g--),g<=d)return e;h*=4}return(new a.od).mb(e,d)}};return e}();a.Tg=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,e=function(){function d(h,e,f){this.version=2;this.resourceTimingInfo={};this.je={};this.ke={};this.$e={};this.af={};this.uc=[];this.jh=function(d,h,e){if(d&&h&&0<h.length){this.fk=
d;for(var f=new c,n=new c,g=0;g<h.length;g++){var m=h[g],k=a.utils.parseURI(a.utils.M.aa(m.name)),l=m.initiatorType,A=b.ya.ae(k),B=new b.ld(m);this.uc.push({u:this.lk(k),i:f.Yd(this.ke,l),r:n.Yd(this.af,A),f:B.Wd,o:this.di(0===g&&m.isBase,B.Ie,d,e),m:B.marks,e:a.utils.isDefined(m.encodedBodySize)?m.encodedBodySize:-1,d:a.utils.isDefined(m.decodedBodySize)?m.decodedBodySize:-1,s:a.utils.isDefined(m.transferSize)?m.transferSize:-1,p:a.utils.isDefined(m.nextHopProtocol)?m.nextHopProtocol:""})}}};var g=
d.ei();this.wh(g,h);h=this.Kj(g,h);this.jh(e||a.monitor.perfMonitor.navTiming&&a.monitor.perfMonitor.navTiming.navigationStart,h,f);this.clearResourceTimings()}d.Xb=function(){var h=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.sampler;d.Jj=h&&"FirstN"==h?new b.eg:h&&"TopN"==h?new b.od:new b.Tg};d.prototype.he=function(a,d){a[d]=a[d]?a[d]+1:1};d.prototype.lk=function(d){return a.utils.kk(d,"number"===typeof a.conf.userConf.maxResUrlSegmentLength?a.conf.userConf.maxResUrlSegmentLength:
a.conf.Xf,"number"===typeof a.conf.userConf.maxResUrlSegmentNumber?a.conf.userConf.maxResUrlSegmentNumber:a.conf.Yf,a.conf.Kg,a.conf.Jg)};d.prototype.wh=function(a,d){a&&this.ie(a);if(d&&0<d.length)for(var e=0;e<d.length;e++)this.ie(d[e])};d.prototype.ie=function(d){var e=a.utils.parseURI(a.utils.M.aa(d.name)),e=b.ya.ae(e);this.he(this.je,d.initiatorType);this.he(this.$e,e)};d.prototype.Kj=function(h,e){if(e&&0<e.length){var c=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.maxNum||
a.conf.Fg;h&&c--;e=d.Jj.mb(e,c);h&&e.unshift(h)}return e};d.prototype.di=function(d,e,c,b){return d?1:a.utils.isDefined(b)?Math.round(e+c-b):Math.round(e)};d.prototype.build=function(){return 0==this.uc.length?null:{v:this.version,ic:this.je,it:this.ke,rc:this.$e,rt:this.af,f:b.ld.hi(),t:this.fk,r:this.uc}};d.ei=function(){var d=a.monitor.perfMonitor.navTiming,e=null;if(d){var e={},c;for(c in d)f(d,c)&&(e[c]=d[c]);e.initiatorType="other";e.name=document.URL;e.navigationStart&&!e.startTime&&(e.startTime=
e.navigationStart);e.isBase=!0}return e};d.prototype.clearResourceTimings=function(){a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.clearResTimingOnBeaconSend&&a.monitor.perfMonitor.clearResourceTimings()};return d}();b.ResourceTimingInfoBuilder=e;var c=function(){function a(){this.ej=1}a.prototype.Yd=function(a,d){a[d]||(a[d]=this.ej++);return a[d]};return a}();e.Xb()})(a.events||(a.events={}))})(g||(g={}));(function(a){a.events||(a.events={})})(g||(g={}));(function(a){(function(b){var f=
function(){function e(){}e.prototype.k=function(e,d){void 0===d&&(d={});var h={eventGUID:e.guid(),eventType:e.type(),eventUrl:a.utils.M.aa(e.url()||document.URL),timestamp:a.utils.now()};e.type()!==a.EventType.PageView&&a.utils.mergeJSON(h,{parentGUID:e.parentGUID()||a.correlation.getPageGUID(),parentUrl:a.utils.M.aa(e.parentUrl()||document.URL),parentType:e.parentType()||(a.utils.compareWindows(top,window)?a.EventType.PageView:a.EventType.IFRAME)});var f=a.EventType[e.type()],f=b.Aa.qi(f,a.conf.userConf,
d,a.conf.xa),g;for(g in f)h[g]=f[g];return h};return e}();b.ua=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.isNumber,e=a.utils.isString,c=a.utils.isObject,d=a.utils.Kd,h=a.utils.Zb,n=a.utils.isBoolean,g=function(){function h(){}h.ec=function(d,h){var e=!1;if(c(d)){var b=a.utils.ha(d);if(!b||b.length<=h)e=!0}return e};h.ak=function(a,d,c){if(e(d))if(d.length>c)h.fb(a,c,d.length);else return d;else h.ac(a,"string")};h.hb=function(a,d){return function(e,b,f){if(c(b)){var g,
n;for(n in b)a(b[n])?(g=g||{},g[n]=b[n]):h.ac(e,d,n);if(g){if(h.ec(g,f))return g;h.fb(e,f)}}else h.ac(e,"object")}};h.ac=function(a,h,e){d(a+" dropped because it was not a "+h+(e?", field name "+e:""))};h.fb=function(a,h,e){d("User event info field "+a+" dropped because it is too long"+(e?" ("+e+" exceeds "+h+")":""))};return h}();g.qi=function(d,h,e,b){if(h=h&&h.userEventInfo&&h.userEventInfo[d]){try{var f=a.utils.isFunction(h)?h.call(null,e):h}catch(n){a.exception(n,"M102",d)}if(c(f))return g.rk(f,
b)}};g.rk=function(a,d){var h={},e;for(e in g.Ud)if(e in a){var c=g.Ud[e](e,a[e],d);c&&(h[e]=c)}return h};g.nj=g.hb(e,"string");g.mj=g.hb(h,"integer");g.Ee=g.hb(f,"number");g.lj=g.hb(n,"boolean");g.Ud={userPageName:g.ak,userData:g.nj,userDataLong:g.mj,userDataDouble:g.Ee,userDataBoolean:g.lj,userDataDate:g.Ee};b.Aa=g})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.isDefined,e=function(e){function d(){return null!==e&&e.apply(this,arguments)||this}u(d,e);d.setPageName=
function(a){d.pk=a};d.addUserData=function(a,e){d.Na=d.Na||{};d.Na[a]=e};d.prototype.k=function(h){h=e.prototype.k.call(this,h||new b.PageView);var g=this.ji(),m=this.fi();a.conf.viz&&(g&&a.utils.Lb(document.getElementById(a.conf.viz),g,"navtime"),a.utils.Lb(document.getElementById(a.conf.viz),m,"cookie"));m.PLC=1;g&&(g.PLC=1);a.monitor.ErrorMonitor.hadErrors&&(m.EPM=1,g&&(g.EPM=1));a.utils.mergeJSON(h,{eventGUID:a.correlation.getPageGUID(),eventType:a.utils.compareWindows(top,window)?a.EventType.PageView:
a.EventType.IFRAME,cookieMetrics:m});var k=-1;g&&g.timestamp?k=g.timestamp:m&&m.timestamp&&(k=m.timestamp);0<k&&a.utils.mergeJSON(h,{timestamp:k});g&&(h.metrics=g);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(h.pageReferrer=a.utils.M.aa(document.referrer));g=d.ki();0<g.length&&(h.pageTitle=g);g=a.correlation.ce();null!==g&&(h.serverMetadata=g);a.conf.spa2?0<a.monitor.ga.Va.length?(g=(new b.ResourceTimingInfoBuilder(a.monitor.ga.Va)).build(),a.monitor.ga.Va=[]):g=null:
g=a.monitor.perfMonitor.resTiming?(new b.ResourceTimingInfoBuilder(a.monitor.perfMonitor.resTiming)).build():null;null!==g&&(h.resourceTimingInfo=g);!f(h.userData)&&f(d.Na)&&(b.Aa.ec(d.Na,a.conf.xa)?h.userData=d.Na:b.Aa.fb("userData",a.conf.xa));a.utils.isDefined(h.userPageName)||(h.userPageName=d.pk);d.userPageName=h.userPageName;return h};d.prototype.ji=function(){if(!a.monitor.perfMonitor.navTiming)return null;var h={},e=d.$d(a.monitor.perfMonitor.navTiming,h,"NT"),c=b.metricSpec[a.EventType.PageView],
f;for(f in c){var g=c[f];e.add(g.name,g.start,g.end)}h.timestamp=a.monitor.perfMonitor.navTiming.navigationStart;return h};d.prototype.fi=function(){var h={};a.commands.marks&&(d.$d(a.commands.marks,h,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready"),h.timestamp=a.commands.marks.starttime?a.commands.marks.starttime:a.commands.marks.firstbyte);return h};
d.ki=function(){var d=a.conf.userConf,d=d&&d.page,e;e=d&&"captureTitle"in d?d.captureTitle:!0;var c,b;d&&(c="title"in d,b=d.title);c=e?c?a.utils.isFunction(b)?b():b:document.title:"";if(a.utils.isString(c))return c;a.utils.Kd("Ignoring wrong type of page title: "+typeof c);return""};d.ih=function(d,e,c,b,f,g){e=b[e];c=b[c];e&&c?f[d]=c-e:a.log("M103",g,d,e,c)};d.$d=function(a,e,c){var b={add:function(f,g,p){d.ih(f,g,p,a,e,c);return b}};return b};return d}(b.ua);b.X=e})(a.events||(a.events={}))})(g||
(g={}));(function(a){(function(b){(function(b){function e(h,b){var f,k=b[h],r=typeof k;t.push(h);var B=s[t.join(".")];if(a.utils.isFunction(B))f=B(k);else switch(r){case "string":f="number"==typeof B?q(k,d,B):d(k);break;case "number":f=m(k);break;case "object":if(k)if(a.utils.isArray(k))f=g(k,!1,!1);else{f=[];for(var y in k)p(k,y)&&(r=e(y,k))&&(c(h)&&"timestamp"==y||f.push({eb:y,v:r}));if(c(h)){for(k=0;k<f.length;k++)f[k]=f[k].eb+d(":")+f[k].v;f=d("{")+f.join(d(","))+d("}")}else{for(k=0;k<f.length;k++)y=
f[k],r=y.eb,a.conf.xf||((B=a.conf.we[y.eb])?r=B:a.error("M104",y.eb)),f[k]=r+"="+y.v;f=f.join("&")}}else f=null}t.pop();return f}function c(a){return"navOrXhrMetrics"==a||"cookieMetrics"==a}function d(a){return"undefined"===typeof a||null===a||0===a.length?null:encodeURIComponent(a)}function h(a){return encodeURIComponent(encodeURIComponent(a))}function g(a,h,b){void 0===h&&(h=!1);void 0===b&&(b=!0);if(0===a.length)return null;var c=[];if(h)c=a;else for(h=0;h<a.length;h++)c.push(e(h,a));return d("[")+
c.join(d(","))+d(b?">":"]")}function m(a){a=Math.round(a);a<b.hd&&(a=b.hd);a>b.ed&&(a=b.ed);return d(a)}function k(a,e){if(a>e||0>a)a=b.Qg;return d(a)}function q(d,e,h,b){void 0===b&&(b=!0);if("undefined"===typeof d||null===d||0===d.length)return null;var c=3<=h?"...":"";a.assert(h>=c.length);for(var f=!1,g=null;;){try{g=e(d);if(null===g)return null;if(g.length<=h)break}catch(n){}var m;f?m=d.length-1:(f=!0,m=h-=c.length);var k=b?0:Math.max(d.length-m,0);d=d.substr(k,m)}f&&(g=b?g+c:c+g);return g}function r(d,
e,h){if(0==h)return b.vb;if(e<d)return 0;e=b.vb+(e-d)/h;a.assert(e>=b.vb);a.log("M105",d,e);return e}var p=a.utils.hasOwnPropertyDefined;b.Qg=-1;b.wa=180;b.Hg=50;b.Ig=50;b.Bg=40;b.vb=50;b.qg=50;b.gd=128;b.wg=30;b.xg=30;b.vg=30;b.Dg=8;b.hd=-99999;b.ed=999999;b.rg=2E3;b.Gg=2;b.sg=99999999;var s={".pageUrl":b.wa,".parentPageUrl":b.wa,".pageReferrer":b.wa,".pageTitle":b.Hg,".userPageName":b.Ig,".geoCountry":b.wg,".geoRegion":b.xg,".geoCity":b.vg,".localIP":b.Dg,".otherClientRequestGUIDs":function(a){a=
a||[];var d=a.slice(0,b.Gg);return g(d,!1,d.length<a.length)},".btTime":function(d){d=d||[];for(var e=d.slice(0,a.conf.tg),h=[],c=0;c<e.length;c++){var q=e[c];h.push(g([k(Number(q[0]),b.sg),m(q[1]),m(q[2])],!0,!1))}return g(h,!0,e.length<d.length)},".ajaxError":function(a){return g([h(a[0]),q(a[1],h,b.qg)],!0,!1)},".userData":function(a){a=a||[];for(var d=!1,e=0,c=[],m=0;m<a.length;m++){var k=a[m];c[m]=g([h(k[0]),h(k[1])],!0,!1);e+=c[m].length;if(e>b.gd){d=!0;break}}for(;;){a=g(c,!0,d);if(null===
a||a.length<=b.gd)return a;c.pop();d=!0}}},t=[];b.Ph=function(d,c){void 0===c&&(c=!0);t=[];var k=[];d.errors&&(k=d.errors,d.errors=null);var s=e("",{"":d});if(k&&0<k.length){for(var p=r(c?870:354,b.rg-s.length,k.length),B=[],y=0;y<k.length;y++){var u=k[y],x=a.utils.M.Td(a.utils.M.aa(u[0]));B.push(g([q(x,h,b.Bg,!1),a.utils.Zb(u[1])?m(u[1]):-1,q(u[2],h,p)],!0,!1))}k=g(B,!0,!1);s+="&errors="+k}return s};b.$k=e;b.Al=d;b.element=h;b.Uk=g;b.Wk=m;b.ol=k;b.truncate=q;b.vl=r})(b.bd||(b.bd={}))})(a.beacons||
(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,e=a.utils.Ua,c=function(){function d(){}d.prototype.gb=function(e,c,f){for(var g=[],q=[],r=null,p=[],s=0;s<e.length;s++){var t=e[s];if(t.eventType===a.EventType.Error){var u=t;q.push([t.eventUrl+"",a.utils.Zb(u.line)?u.line:void 0,u.message+""])}else{if(t.eventType===a.EventType.PageView||t.eventType===a.EventType.IFRAME)r=t;p.push(t)}}e=p;if(0<q.length)for(r&&(r.errors=q.splice(0,a.conf.zg));0<q.length;)t=
q.splice(0,a.conf.yg),r=d.qj.k(),r.errors=t,r.isErrorEvent=!0,r.cookieMetrics=null,r.metrics=null,r.resourceTimingInfo=null,e.push(r);for(q=0;q<e.length;q++)t=e[q],a.log("M106"),t.resourceTimingInfo=null,d.ai(t,c,f),r=d.transform(t),g.push(b.bd.Ph(r,t.isErrorEvent));return g};d.ai=function(d,e,b){d.ver=this.kg;d.rootGUID=b.Rb();d.geo=e;d.dataType="R";d.eom=1;d.eumAppKey=a.conf.appKey;d.PLC=1};d.transform=function(a){var e={};d.Cf("",{"":a},e);return e};d.Cf=function(h,b,c){b=b[h];var g=d.se[h];if("metrics"===
h||"cookieMetrics"===h)c[g]=b;else if("btTime"===h&&a.utils.isArray(b)&&0<b.length){h=[];for(var q=0;q<b.length;q++)h.push([b[q].id,b[q].duration,b[q].ert]);c[g]=h}else if("userData"===h&&a.utils.isObject(b))c[g]=a.utils.$i(b);else if(!(h&&-1<e(["userDataLong","userDataDouble","userDataBoolean","userDataDate"],h)))if(a.utils.isObject(b))for(q in b)f(b,q)&&d.Cf(q,b,c);else d.se[h]&&("eventType"===h&&b>a.EventType.Ajax&&(b=a.utils.compareWindows(top,window)?a.EventType.PageView:a.EventType.IFRAME),
c[g]=b)};return d}();c.qj=new a.events.X;c.kg=3;c.se={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",
dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};b.og=c})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}a.prototype.send=function(){};return a}();a.cg=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){var f=
function(){function a(){}a.prototype.gb=function(){return null};return a}();a.bg=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(a){this.Xi=a}e.prototype.send=function(e){try{this.Xi.postMessage(a.utils.ha(e)),a.log("M107"),b.numBeaconsSent+=1}catch(d){a.log("M108")}};return e}();b.hg=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.gb=function(e,d,h){e={ver:a.conf.agentVer,dataType:"R",
rootGUID:h.Rb(),events:e};a.channel.L.K&&a.channel.L.K.id&&(e.agentId=a.channel.L.K.id);d&&(e.geo=d);return e};return e}();b.gg=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){var b=function(){function b(){}b.Jd=function(e,b){if(!e)return null;var d=e.ADRUM.lifecycle;if(!d||!d.getPhaseCallbackTime)return null;var h=b.getPhaseCallbackTime("AT_ONLOAD"),d=d.getPhaseCallbackTime("AT_ONLOAD"),f=null==d;return null==h?(a.error("M109"),null):a.lifecycle.getPhaseID(f||h<=d?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};
return b}();a.Sg=b;a.cPLPI=b.Jd})(g||(g={}));(function(a){(function(b){var f=function(){function e(e){this.ready=!1;this.geoResolverUrl=e;a.utils.isString(e)&&0<a.utils.trim(e).length&&(this.geoResolverUrl=e+"/resolve.js")}e.prototype.init=function(e){this.channel=e;if(this.Hb()&&(a.geo=this.Fc(),this.ph()||this.ib()&&!this.Xd())){this.channel.xc(a.geo.result);return}this.Xd()?(this.ib()&&(this.geoResolverUrl+="?ip="+encodeURIComponent(a.conf.userConf.geo.localIP)),this.ok()):(this.ready=!0,this.channel.onResolverReady())};
e.prototype.Hb=function(){return a.utils.isDefined(a.conf.userConf)&&a.utils.isDefined(a.conf.userConf.geo)};e.prototype.ib=function(){return this.Hb()&&a.utils.isDefined(a.conf.userConf.geo.localIP)&&!a.utils.isDefined(a.conf.userConf.geo.city)&&!a.utils.isDefined(a.conf.userConf.geo.region)&&!a.utils.isDefined(a.conf.userConf.geo.country)};e.prototype.Fc=function(){return{failed:!1,result:{country:a.conf.userConf.geo.country,region:a.conf.userConf.geo.region,city:a.conf.userConf.geo.city,localIP:this.Rh(a.conf.userConf.geo.localIP)}}};
e.prototype.ph=function(){return this.Hb()&&a.utils.isDefined(a.conf.userConf.geo.localIP)&&a.utils.isDefined(a.conf.userConf.geo.city)&&a.utils.isDefined(a.conf.userConf.geo.region)&&a.utils.isDefined(a.conf.userConf.geo.country)};e.prototype.Xd=function(){return a.utils.isString(this.geoResolverUrl)&&0<a.utils.trim(this.geoResolverUrl).length};e.prototype.Rh=function(a){if(null==a||0==a.length)return null;a=a.split(".");if(4!=a.length)return null;for(var d=[],e=0;e<a.length;e++){var b=parseInt(a[e]);
if(isNaN(b)||0>b||255<b)return null;d.push(("0"+b.toString(16)).slice(-2))}return d.join("")};e.prototype.ok=function(){a.geo={failed:!1,result:null};a.utils.loadScriptAsync(this.geoResolverUrl);var b=this;a.utils.tryPeriodically(e.Cb,function(){return b.isReady()},function(){b.onReady()},function(){b.fc()})};e.prototype.isReady=function(){this.ready||(this.ready=a.geo&&(a.geo.failed||null!==a.geo.result))||a.log("M110");return this.ready};e.prototype.onReady=function(){a.geo.failed?(a.log("M111"),
this.ib()&&(a.geo=this.Fc())):(a.assert("object"===typeof a.geo.result),a.log("M112",a.geo.result));a.geo&&a.geo.result&&this.channel.xc(a.geo.result);this.channel.onResolverReady()};e.prototype.fc=function(){a.log("M113");this.ib()&&(a.geo=this.Fc());a.geo&&a.geo.result&&this.channel.xc(a.geo.result);this.ready=!0;this.channel.onResolverReady()};e.Cb=function(a){return 10<a?-1:[1,50,100,500][a-1]||1E3};return e}();b.fg=f})(a.channel||(a.channel={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.ready=
!1;this.channel=null}e.prototype.init=function(b){this.channel=b;e.N=e.N||e.ci();this.ready=!e.N.ab;var d=this;if(e.N.ab)a.log("M114"),e.N.ab.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){a.log("M115");d.ready=!0;d.onReady()});else d.onReady()};e.prototype.isReady=function(){this.isReady||a.log("M116");return this.ready};e.prototype.onReady=function(){this.channel.Oj(e.N);this.channel.onResolverReady()};e.ci=function(){for(var b=window,d,h=e.pe(b),f=window;f.parent&&!a.utils.compareWindows(f,
f.parent);){f=f.parent;h=h||e.pe(f);try{f.ADRUM&&(d=d||f,b=f)}catch(g){}}return new a.Pf(d,b,h)};e.pe=function(a){try{return 0==a.document.URL.indexOf("https:")}catch(d){}};return e}();f.N=null;b.Qf=f})(a.channel||(a.channel={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(d,h,c){this.events=[];this.ca={};this.Ya=NaN;this.$=[];this.Ob=!1;this.bufferMode=a.conf.userConf&&a.conf.userConf.channel&&"undefined"!==typeof a.conf.userConf.channel.bufferMode?a.conf.userConf.channel.bufferMode:
!0;this.nb=-1;this.gk=d;this.rh=h;this.$.push(new b.fg(c));this.$.push(new b.Qf);this.$.push(new b.L)}e.create=function(){var d,h;d=e.vj();a.utils.isDefined(d)?(d=new a.beacons.hg(d),h=new a.beacons.gg):e.Ei()&&!a.conf.sendImageBeacon?(d=new a.beacons.Tf,h=new a.beacons.Sf):e.Ji()?(d=new a.beacons.cg,h=new a.beacons.bg):(d=new a.beacons.pg,h=new a.beacons.og);d=new e(d,h,a.conf.geoResolverUrl);d.init();return d};e.prototype.init=function(){for(var a=0;a<this.$.length;a++)this.$[a].init(this)};e.prototype.uk=
function(e){return(e.parentType===a.EventType.VPageView||e.parentType===a.EventType.NG_VIRTUAL_PAGE)&&null!==this.ca[e.parentGUID]};e.prototype.oc=function(e){var h=e.parentGUID;if(!a.utils.isDefined(this.ca[h])){this.ca[h]=[];var b=this,c=e.eventGUID;setTimeout(function(){b.Kb(c)},1E4)}this.ca[h].push(e)};e.prototype.report=function(d){d.sequenceId=a.hf.Hd.gi();d.timestamp=d.timestamp||a.utils.now();this.uk(d)?this.oc(d):this.events.push(d);1==this.events.length&&(this.Ya=a.utils.now());var h=d.parentGUID;
h&&h!==a.correlation.getPageGUID()||this.Kb(d.eventGUID);e.Ii(d)&&(this.Ob=!0);this.Ec()};e.prototype.Kb=function(a){var e=this.ca[a];this.ca[a]=null;if(e&&0!=e.length)for(this.events=this.events.concat(e),a=0;a<e.length;a++)this.Kb(e[a].eventGUID)};e.prototype.Li=function(e){return e.eventType===a.EventType.PageView||e.eventType===a.EventType.IFRAME};e.prototype.sh=function(){for(var e=0;e<this.events.length;e++){var h=this.events[e];if(this.Li(h)){var b=this.N.ab;b&&(h.parentLifecyclePhase=a.Sg.Jd(b,
a.lifecycle),h.parentGUID=b.ADRUM.correlation.getPageGUID(),h.parentUrl=a.utils.M.aa(b.document.URL),a.utils.isDefined(b.ADRUM.events.X.userPageName)&&(h.rj=b.ADRUM.events.X.userPageName),h.parentType=a.utils.compareWindows(top,b)?a.EventType.PageView:a.EventType.IFRAME)}}};e.prototype.Mj=function(){if(0==this.events.length)a.log("M117");else{this.sh();var e=this.Gc(this.events,this.N),h=this.rh.gb(this.events,this.bi,this.N);this.gk.send(h,e);this.events=[];this.Ya=Number.POSITIVE_INFINITY}};e.prototype.onResolverReady=
function(){this.Ec()};e.prototype.xc=function(a){this.bi=a};e.prototype.Oj=function(a){this.N=a};e.prototype.addResolver=function(a){a.init(this);this.$.push(a)};e.prototype.Fj=function(){for(var a=0;a<this.$.length;a++)if(!this.$[a].isReady())return!1;return!0};e.prototype.re=function(){return this.Ya+a.conf.dd>a.utils.now()};e.prototype.Qi=function(){return this.events.length<a.conf.ug};e.prototype.Gc=function(e,h){if(h.Gc||a.conf.userConf.useHTTPSAlways)return!0;for(var b=0;b<e.length;b++){var c=
e[b];if(c.eventUrl&&0==c.eventUrl.indexOf("https:"))return!0}return!1};e.prototype.getEventsWithParentGUID=function(a){return this.ca[a]||[]};e.prototype.Ec=function(){if(this.Fj())if(this.tk()){if(this.re()&&0<this.events.length&&0>this.nb){var e=this;this.nb=setTimeout(function(){e.Ec()},a.conf.dd+this.Ya-a.utils.now())}}else clearTimeout(this.nb),this.nb=-1,this.Ob=!1,this.Mj()};e.Ii=function(e){return e.eventType===a.EventType.PageView||e.eventType===a.EventType.IFRAME||e.eventType===a.EventType.VPageView};
e.prototype.tk=function(){return this.bufferMode&&!this.Ob&&this.Qi()&&this.re()};e.Ei=function(){var a="undefined"!==typeof JSON&&!(!JSON||!JSON.stringify);return window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&a};e.wj=function(){if(a.utils.isDefined(window.webkit)&&a.utils.isDefined(window.webkit.messageHandlers)&&a.utils.isDefined(window.webkit.messageHandlers.ADEUM_js_handler)&&a.utils.isFunction(window.webkit.messageHandlers.ADEUM_js_handler.postMessage))return window.webkit.messageHandlers.ADEUM_js_handler};
e.uj=function(){if(a.utils.isDefined(window.ADEUM_js_handler)&&a.utils.isFunction(window.ADEUM_js_handler.postMessage))return window.ADEUM_js_handler};e.vj=function(){return e.uj()||e.wj()};e.Ji=function(){return a.conf.userConf&&a.conf.userConf.beacon&&a.conf.userConf.beacon.neverSendImageBeacon};return e}();b.Channel=f;var e=f.create();b.report=function(a){e.report(a)};b.addResolver=function(a){e.addResolver(a)};b.getEventsWithParentGUID=function(a){return e.getEventsWithParentGUID(a)}})(a.channel||
(a.channel={}))})(g||(g={}));(function(a){var b=function(){function b(){}b.Ne=function(){return window.attachEvent?a.utils.isFunction(window.addEventListener)?this.Hc:this.qf:this.wf};b.Me=function(e){var c=null;switch(b.Ne()){case b.wf:c=e.parentPhase();break;case b.Hc:c=a.lifecycle.findPhaseAtNominalTime(e.getSendTime());break;case b.qf:c=null}return a.lifecycle.getPhaseID(c)};return b}();b.wf="uCT";b.Hc="uNET";b.qf="tIA";a.Ra=b})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,
e=function(e){function d(){return null!==e&&e.apply(this,arguments)||this}u(d,e);d.prototype.k=function(h){var f=e.prototype.k.call(this,h,d.getContext(h)),g=h.url(),k=h.getSendTime(),q=h.getFirstByteTime(),r=h.getRespAvailTime(),p=h.getRespProcTime();a.assert(null!==g&&null!==k&&null!==q&&null!==r&&null!==p,"missing some pieces of XHR data: url="+g+", send="+k+", fbt="+q+", rat="+r+", eut="+p+", parentPhase="+h.parentPhase());if(null===g||null===k||null===q||null===r||null===p)return null;g=h.error();
k={PLC:1,FBT:q-k,DDT:r-q,DPT:p-r,PLT:p-k,ARE:g?1:0};q=h.url();if(!d.Wi(k,q))return null;a.conf.viz&&a.utils.Lb(document.getElementById(a.conf.viz),k,"xhr");a.utils.mergeJSON(f,{eventUrl:a.utils.M.aa(q),parentType:h.parentType()||a.EventType.PageView,parentLifecyclePhase:h.parentPhaseId(),metrics:k,method:h.method(),timestamp:h.timestamp(),ajaxError:g&&[g.status,g.msg||""],xhrStatus:h.xhrStatus()});(h=h.parameter())&&b.Aa.ec(h,a.conf.xa)?f.parameter=h:h&&b.Aa.fb("parameter",a.conf.xa);a.utils.Pj(f,
b.X.userPageName);return f};d.getContext=function(a){return{url:a.url()||"",method:a.method()||""}};d.Wi=function(e,d){for(var b in e)if(f(e,b)){var c=e[b];if(0>c)return a.error("XHR "+b+" ["+c+"] "+d),!1}return!0};return d}(b.ua);b.qd=e})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=function(e){function b(){return null!==e&&e.apply(this,arguments)||this}u(b,e);b.prototype.k=function(d){var b=e.prototype.k.call(this,d);b&&(d=d.allResponseHeaders()||"",(d=a.correlation.pi(d))&&
null!==d&&null!==d.clientRequestGUID&&(b.eventGUID=d.clientRequestGUID),null!==d&&(b.serverMetadata=d));return b};return b}(b.qd);b.Jf=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=function(e){function c(){return null!==e&&e.apply(this,arguments)||this}u(c,e);c.prototype.k=function(d){var h=e.prototype.k.call(this,d);a.utils.mergeJSON(h,{message:d.msg()||"",timestamp:d.timestamp(),line:d.line(),stack:d.stack(),parentPageName:b.X.userPageName});a.utils.isString(h.userPageName)||
(h.userPageName=h.rj);return h};return c}(b.ua);b.Rg=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){(function(f){f.build=function(e){var c={},d=a.metricSpec[e.type()],h;for(h in d){var f=d[h];if(null!==f.name&&e.perf.getEntryByName(f.start)&&e.perf.getEntryByName(f.end)){e.perf.measure(f.name,f.start,f.end);var g=e.perf.getEntryByName(f.name);c[f.name]=g&&0<=g.duration&&g.duration||null}}for(h in c)c[h]=Math.round(c[h]);return c}})(a.wb||(a.wb={}))})(a.events||(a.events={}))})(g||
(g={}));(function(a){(function(a){var f=function(e){function f(){return null!==e&&e.apply(this,arguments)||this}u(f,e);f.prototype.k=function(d){var h=e.prototype.k.call(this,d),f=a.wb.build(d);f.PLC=1;h.metrics=f;h.timestamp=d.timestamp();d=(new a.ResourceTimingInfoBuilder(d.resTiming())).build();null!==d&&(h.resourceTimingInfo=d);return h};return f}(a.ua);a.pd=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(e){function f(){return null!==e&&e.apply(this,arguments)||
this}u(f,e);f.prototype.k=function(d){var h=e.prototype.k.call(this,d),f=a.wb.build(d);f.PLT=d.timestamp()-d.startTime;f.PLC=1;h.metrics=f;h.timestamp=d.timestamp();d=(new a.ResourceTimingInfoBuilder(d.resTiming(),null,d.startTime)).build();null!==d&&(h.resourceTimingInfo=d);return h};return f}(a.ua);a.Rf=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}u(b,a);b.prototype.k=function(d){var b=a.prototype.k.call(this,
d);b&&(b.metrics.VDC=d.digestCount()||0);return b};return b}(a.pd);a.Pg=f})(a.events||(a.events={}))})(g||(g={}));(function(a){var b=a.events||(a.events={});b.Ve={};a=[{ia:b.PageView,ea:new b.X},{ia:b.Ajax,ea:new b.qd},{ia:b.AdrumAjax,ea:new b.Jf},{ia:b.Error,ea:new b.Rg},{ia:b.VPageView,ea:new b.pd},{ia:b.Qc,ea:new b.Rf},{ia:a.ng.NgVPageView,ea:new b.Pg}];for(var f=0;f<a.length;f++){var e=a[f];e.ia.prototype._regId=f;b.Ve[f]=e.ea}})(g||(g={}));(function(a){(function(b){b.reportEvent=function(b){var e=
a.events.Ve[b._regId];e?(e=e.k(b),a.utils.isDefined(e)&&(a.log("M119",a.EventType[b.type()]),a.channel.report(e))):a.log("M118"+a.EventType[a.eventType])}})(a.reporter||(a.reporter={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.ready=!1}e.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};e.prototype.isReady=function(){this.ready||a.log("M120");return this.ready};e.prototype.init=function(a){this.channel=a};return e}();b.fh=f})(a.commands||(a.commands=
{}))})(g||(g={}));(function(a){(function(b){var f=new b.fh;a.channel.addResolver(f);b.marks={};b.mark=function(e,f){a.log("M121",e,f);b.marks[e]=f};b.reportOnload=function(e){setTimeout(function(){a.log("M122");a.reporter.reportEvent(e);f.onReady()},a.conf.dh)};b.reportEvent=function(){a.reporter.reportEvent.apply(a.reporter,arguments)};b.addResolver=function(e){a.channel.addResolver(e)};b.reportXhr=function(e){a.log("M123");a.Ra.Ne()==a.Ra.Hc?(a.log("M124"),setTimeout(function(){e.parentPhaseId(a.Ra.Me(e));
a.reporter.reportEvent(e)},0)):(e.parentPhaseId(a.Ra.Me(e)),a.reporter.reportEvent(e))};b.listenForOkToSendChildFrameBeacons=function(e){a.log("M125");try{e()}catch(b){a.exception(b,"M126")}};b.reportPageError=function(e){var b=e.url();a.log("M127",e.msg(),b,e.line(),e.stack());b&&0!==b.length||e.url("CROSSORIGIN");a.reporter.reportEvent(e)};b.setPageName=function(e){a.utils.isString(e)&&0<a.utils.trim(e).length&&a.events.X.setPageName(e)};b.addUserData=function(e,b){a.events.X.addUserData(e,b)};
b.call=function(a){a()}})(a.commands||(a.commands={}))})(g||(g={}));(function(a){(function(a){a.Sd=function(f){return encodeURIComponent(a.M.kj(f))}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.setUp=function(){this.bj();a.utils.addEventListener(window,"pagehide",e.Nc);a.utils.addEventListener(window,"beforeunload",e.Nc);a.utils.addEventListener(window,"unload",e.Nc)};e.prototype.bj=function(){(this.startTime=e.Zh()||e.Yh())&&a.commands.mark("starttime",
this.startTime)};e.Zh=function(){var e;try{if(a.utils.isDefined(window.external)&&a.utils.isNumber(window.external.pageT))e=(new Date).getTime()-window.external.pageT;else if(a.utils.isDefined(window.ee)&&a.utils.isFunction(window.ee.pageT)){var d=window.ee.pageT();a.utils.isNumber(d)&&(e=(new Date).getTime()-d)}else a.utils.isDefined(window.chrome)&&a.utils.isFunction(window.chrome.csi)&&(d=window.chrome.csi(),a.utils.isDefined(d)&&a.utils.isNumber(d.pageT)&&(e=(new Date).getTime()-d.pageT));e&&
(e=Math.round(e),a.log("M128",e))}catch(b){a.exception(b,"M129")}return e};e.Yh=function(){var e=a.correlation.startTimeCookie;if(e){a.log("M130",e.startTime,e.startPage);var d=a.utils.Sd(document.referrer);if(d===e.startPage)if(isNaN(e.startTime))a.log("M131",e.startTime);else return e.startTime;else a.log("M132",d,e.startPage)}else a.log("M133")};e.Mh=function(e,d){var b=document.domain,f="https:"===document.location.protocol,g="ADRUM=s="+Number(new Date)+"&r="+a.utils.Sd(document.location.href),
k=g+";path=/";f&&(k+=";secure");a.log("M134",g);if(!a.conf.useStrictDomainCookies){for(var f=e(),b=b.split("."),q="",r=b.length-1;0<=r;r--){q="."+b[r]+q;a.log("M135",q);d(k+";domain="+q);var p=e();if(p!=f&&0<=p.indexOf(g)){a.log("M136");a.log("M137");return}}a.log("M138")}a.log("M139");d(k);a.log("M140")};return e}();f.Nc=function(){var a=!1;return function(){a||(a=!0,f.Mh(function(){return document.cookie},function(a){document.cookie=a}))}}();b.Kk=f;b.Zj=new f})(a.monitor||(a.monitor={}))})(g||(g=
{}));(function(a){a.log("M141");a.monitor.Zj.setUp();a.q.processQ();a.initEXTDone=!0;a.log("M142")})(g||(g={}))}};})();
